sonar.projectKey=bookap
sonar.projectName=Kitaplik App
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__tests__/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.html,**/dist/**,**/build/**,**/.expo/**,**/test-*.js,**/scripts/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_061128ba74268577334891dbc2d28ca6e1bf028f
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info