sonar.projectKey=book
sonar.projectName=Kitaplik App
sonar.projectVersion=1.0.0
sonar.sources=app,components,constants,context,hooks,services,i18n,utils
sonar.exclusions=**/node_modules/**,**/.expo/**,**/assets/**,**/*.test.ts,**/*.spec.ts,**/*.test.js,**/*.d.ts
sonar.tests=.
sonar.test.inclusions=test-*.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_752e4b323a8a2983f1ecfd3898735282d538c950